import os
from pathlib import Path, PurePosixPath, PureWindowsPath


ALLOWED_PLACEHOLDER_ARTIFACT_SUFFIXES = {
    ".json",
    ".csv",
    ".tsv",
    ".txt",
    ".md",
    ".html",
    ".png",
    ".pdf",
}
_REPO_ROOT = Path(__file__).resolve().parents[3]
_DEFAULT_OUTPUT_ROOT = _REPO_ROOT / "data" / "outputs"


_PLACEHOLDER_ARTIFACTS = [
    {
        "name": "run_summary.json",
        "artifact_type": "run_summary",
        "description": "Planned placeholder run summary. No real execution summary has been generated yet.",
    },
    {
        "name": "qc_summary.json",
        "artifact_type": "qc_summary",
        "description": "Planned placeholder QC summary. No real QC output has been generated yet.",
    },
    {
        "name": "differential_expression_results.csv",
        "artifact_type": "differential_expression_results",
        "description": "Planned placeholder differential expression results table. No real RNA-seq results have been generated yet.",
    },
    {
        "name": "report.md",
        "artifact_type": "analysis_report",
        "description": "Planned placeholder analysis report. No real report file has been generated yet.",
    },
]


def get_output_root() -> Path:
    configured_root = os.environ.get("BIOINFO_OUTPUT_ROOT", "").strip()
    root = Path(configured_root) if configured_root else _DEFAULT_OUTPUT_ROOT
    return root.expanduser().resolve(strict=False)


def validate_task_id_for_path(task_id: str) -> str:
    if not isinstance(task_id, str) or not task_id.strip():
        raise ValueError("Task ID must be a non-empty path segment.")

    if "\x00" in task_id:
        raise ValueError("Task ID must not contain null bytes.")

    if "/" in task_id or "\\" in task_id:
        raise ValueError("Task ID must not contain path separators.")

    if ":" in task_id:
        raise ValueError("Task ID must not contain colons.")

    if _has_path_traversal(task_id):
        raise ValueError("Task ID must not contain path traversal.")

    return task_id


def get_task_output_dir(task_id: str) -> Path:
    safe_task_id = validate_task_id_for_path(task_id)
    output_root = get_output_root()
    output_dir = (output_root / "tasks" / safe_task_id).resolve(strict=False)
    if not _is_relative_to(output_dir, output_root):
        raise ValueError("Task output directory escapes output root.")
    return output_dir


def ensure_task_output_dir(task_id: str) -> Path:
    output_dir = get_task_output_dir(task_id)
    output_dir.mkdir(parents=True, exist_ok=True)
    return output_dir


def get_task_artifact_relative_path(task_id: str, filename: str) -> str:
    safe_task_id = validate_task_id_for_path(task_id)
    safe_filename = _validate_artifact_filename(filename)
    return PurePosixPath("tasks", safe_task_id, safe_filename).as_posix()


def resolve_task_artifact_path(task_id: str, filename: str) -> Path:
    task_output_dir = get_task_output_dir(task_id)
    safe_filename = _validate_artifact_filename(filename)
    artifact_path = (task_output_dir / safe_filename).resolve(strict=False)
    if not _is_relative_to(artifact_path, task_output_dir):
        raise ValueError("Artifact path escapes task output directory.")
    return artifact_path


def list_placeholder_artifact_specs(task_id: str) -> list[dict]:
    specs: list[dict] = []
    for artifact in _PLACEHOLDER_ARTIFACTS:
        filename = artifact["name"]
        specs.append(
            {
                "name": filename,
                "relative_path": get_task_artifact_relative_path(task_id, filename),
                "artifact_type": artifact["artifact_type"],
                "exists": resolve_task_artifact_path(task_id, filename).is_file(),
                "description": artifact["description"],
                "limitations": [
                    "This is a planned placeholder artifact path only.",
                    "No real RNA-seq output file is generated by Phase 3.5.",
                ],
            }
        )
    return specs


def _validate_artifact_filename(filename: str) -> str:
    if not isinstance(filename, str) or not filename.strip():
        raise ValueError("Artifact filename must be a non-empty filename.")

    if "\x00" in filename:
        raise ValueError("Artifact filename must not contain null bytes.")

    if _is_absolute_path(filename):
        raise ValueError("Artifact filename must be relative.")

    if "/" in filename or "\\" in filename:
        raise ValueError("Nested artifact paths are not supported.")

    if ":" in filename:
        raise ValueError("Artifact filename must not contain colons.")

    if _has_path_traversal(filename):
        raise ValueError("Artifact filename must not contain path traversal.")

    suffix = PurePosixPath(filename).suffix.lower()
    if suffix not in ALLOWED_PLACEHOLDER_ARTIFACT_SUFFIXES:
        allowed = ", ".join(sorted(ALLOWED_PLACEHOLDER_ARTIFACT_SUFFIXES))
        raise ValueError(f"Unsupported artifact suffix: {suffix or '<none>'}. Allowed suffixes: {allowed}.")

    return filename


def _is_absolute_path(path_value: str) -> bool:
    posix_path = PurePosixPath(path_value.replace("\\", "/"))
    windows_path = PureWindowsPath(path_value)
    return bool(
        posix_path.is_absolute()
        or windows_path.is_absolute()
        or windows_path.drive
        or Path(path_value).is_absolute()
    )


def _has_path_traversal(path_value: str) -> bool:
    posix_path = PurePosixPath(path_value.replace("\\", "/"))
    windows_path = PureWindowsPath(path_value)
    return ".." in posix_path.parts or ".." in windows_path.parts


def _is_relative_to(path: Path, root: Path) -> bool:
    try:
        path.relative_to(root)
    except ValueError:
        return False
    return True
